"""Add Collection model

Revision ID: 200f6f4330e7
Revises: 4d748616604b
Create Date: 2023-11-29 19:58:15.419741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200f6f4330e7'
down_revision: Union[str, None] = '4d748616604b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('has_website', sa.Boolean(), nullable=True),
    sa.Column('has_discord', sa.Boolean(), nullable=True),
    sa.Column('has_twitter', sa.Boolean(), nullable=True),
    sa.Column('is_badged', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol'),
    schema='magiceden'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections', schema='magiceden')
    # ### end Alembic commands ###
