"""DB schema init

Revision ID: 25c9cc28e660
Revises: 
Create Date: 2023-11-25 12:21:15.578944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from config import SCHEMA

# revision identifiers, used by Alembic.

revision: str = '25c9cc28e660'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text(f'CREATE SCHEMA IF NOT EXISTS {SCHEMA};'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.text(f'DROP SCHEMA IF EXISTS {SCHEMA};'))
    # ### end Alembic commands ###
