"""Models init

Revision ID: 4d748616604b
Revises: 25c9cc28e660
Create Date: 2023-11-25 14:58:03.837049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d748616604b'
down_revision: Union[str, None] = '25c9cc28e660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_amount', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='magiceden'
    )
    op.create_table('tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='magiceden'
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('token_mint', sa.String(), nullable=False),
    sa.Column('collection_symbol', sa.String(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('block_time', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('buyer_referral', sa.String(), nullable=True),
    sa.Column('seller_referral', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price_info_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['price_info_id'], ['magiceden.price_info.id'], ),
    sa.ForeignKeyConstraint(['token_mint'], ['magiceden.tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='magiceden'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities', schema='magiceden')
    op.drop_table('tokens', schema='magiceden')
    op.drop_table('price_info', schema='magiceden')
    # ### end Alembic commands ###
