name: "Dash Test, Build, Deploy"
 
on:
 push:
   paths:
   - apps/dash/**
   - .github/workflows/dash.yml

jobs:
  test:
   name: "Dash test"
   runs-on: ubuntu-latest

   steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Test
       run: echo "Tests passed successfully"

  build:
   name: "Dash build"
   runs-on: ubuntu-latest
   container:
     image: docker://docker:dind
     volumes:
       - ${{ github.workspace }}:/app

   steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Build
       run: export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA") && cd apps/dash/ && docker build -t registry.digitalocean.com/masters-degree/dash:${IMAGE_TAG}

     - name: Push
       run: docker login registry.digitalocean.com --username=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password=${{ secrets.PASSWORD }}

  deploy:
   name: "Dash deploy"
   runs-on: ubuntu-latest
   container:
     image: docker://alpine/helm:3.11.1
     volumes:
       - ${{ github.workspace }}:/app

   steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Deploy
       run: export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA") && cd apps/dash/ && mkdir -p /github/home/.kube && echo $KUBECONFIG_FILE | base64 -d  > /github/home/.kube/config && helm upgrade -i --dry-run dash helm -f helm/values.yaml -n default --set image.tag=${IMAGE_TAG}
       env:
         KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

     - name: Deploy
       if: github.ref == 'refs/heads/master'
       run: export IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA") && cd apps/dash/ && mkdir -p /github/home/.kube && echo $KUBECONFIG_FILE | base64 -d  > /github/home/.kube/config && helm upgrade -i dash helm -f helm/values.yaml -n default --set image.tag=${IMAGE_TAG}
       env:
         KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}