name: "Helm ingress-nginx"
 
on:
 push:
   paths:
   - infra/helm/ingress-nginx/**
   - .github/workflows/helm-ingress-nginx.yml

jobs:
 helm:
   name: "Helm ingress-nginx"
   runs-on: ubuntu-latest
   container:
     image: docker://alpine/helm:3.11.1
     volumes:
       - ${{ github.workspace }}/infra/helm/ingress-nginx:/opt/app

   steps:
     - name: Deploy
       run: echo ${{ secrets.KUBECONFIG}} > kubeconfig.yaml && helm upgrade -i --dry-run ingress-nginx . -f values.yml -n ingress-ngins
       working-directory: /opt/app
       env:
         KUBECONFIG: "./kubeconfig.yaml"

     - name: Deploy
       if: github.ref == 'refs/heads/master'
       run: echo ${{ secrets.KUBECONFIG}} > kubeconfig.yaml && helm upgrade -i --dry-run ingress-nginx . -f values.yml -n ingress-ngins
       working-directory: /opt/app
       env:
         KUBECONFIG: "./kubeconfig.yaml"
