name: "Helm ingress-nginx"
 
on:
 push:
   paths:
   - infra/helm/ingress-nginx/**
   - .github/workflows/helm-ingress-nginx.yml

jobs:
 helm:
   name: "Helm ingress-nginx"
   runs-on: ubuntu-latest
   container:
     image: docker://alpine/helm:3.11.1

   steps:
     - name: Deploy
       run: cd ${{ github.workspace }}/infra/helm/ingress-nginx && echo $KUBECONFIG_FILE > ../kube.config && pwd && ls -la && helm upgrade -i --dry-run ingress-nginx . -f values.yml -n ingress-nginx --kubeconfig ../kube.config
       env:
         KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

     - name: Deploy
       if: github.ref == 'refs/heads/master'
       run: echo $KUBECONFIG_FILE > ../kube.config && helm upgrade -i --dry-run ingress-nginx . -f values.yml -n ingress-nginx --kubeconfig ../kube.config
       working-directory: /opt/app
       env:
         KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
