name: "Helm ingress-nginx"
 
on:
 push:
   paths:
   - infra/helm/ingress-nginx/**
   - .github/workflows/helm-ingress-nginx.yml

jobs:
 helm:
   name: "Helm ingress-nginx"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: infra/helm/ingress-nginx
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Deploy
       uses: vimeda/helm@v1.7.0
       with:
         helm: "helm3"
         dry-run: true
         release: "ingress-nginx"
         namespace: "ingress-nginx"
         chart: "app"
         token: "${{ github.token }}"
         value-files: "values.yaml"
       env:
         KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"

     - name: Deploy
       if: github.ref == 'refs/heads/master'
       uses: vimeda/helm@v1.7.0
       with:
         helm: "helm3"
         release: "ingress-nginx"
         namespace: "ingress-nginx"
         chart: "app"
         token: "${{ github.token }}"
         value-files: "values.yaml"
       env:
         KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
